config/routes.rb
AskBolt::Application.routes.draw do
root 'posts#index'

resources :users, only: [:new, :create, :edit, :update, :index]
resources :sessions, only:[:create]
resources :posts

get '/login', to: 'sessions#new'
get '/logout', to: 'sessions#new'
post '/logout', to: 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :comments, :as => :commentable, :order => :created_at,
                      :dependent => :destroy

  validates_presence_of :post
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true

  def email=(value)
    value = value.strip.downcase
    write_attribute :email, value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def sign_in(user)
    session[:user_id] = user.id if user.present?
  end

  def current_user
    User.find_by id: session[:user_id] if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all

    if current_user.present?
      @myposts = Post.find_all_by_user_id(current_user.id)
    else

    end
    @recentposts = Post.order("created_at DESC").page(params[:page]).per(4)
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])

  end

  def new
    @post = Post.new

  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to posts_url
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to posts_url
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
  end

  private
  def post_params
    params.require(:post).permit(:post)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email].downcase
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You are signed in!"
      redirect_to root_url
    else
      flash.now[:alert] = "Invalid username and/or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User Created!"
      sign_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @states = State.all
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash.notice = "User has been updated"
      redirect_to users_url
    else
      render "edit"
    end
  end


  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :dob, :street_address, :state, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AskBolt</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar :fixed => :top, :brand => "AskBolt", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Questions" do %>
            <%= menu_item "Ask a Question", new_post_path %>
            <%= menu_item "Browse Questions", posts_path %>
        <% end %>
        <% if current_user.present? %>
          <%= menu_item "Profile", edit_user_path(current_user) %>
        <% end %>
    <% end %>
    <%= menu_group :pull => :right do %>
    <div id="logged-out" >
        <% if current_user.present? %>
          <%= menu_item current_user.email + " Log Out", logout_path, method: :destroy %>
        <% else %>
          <%= link_to 'Register', new_user_path %>
         or
          <%= link_to 'Sign In', login_path %>
        <% end %>
    <% end %>
<% end %>
</div>

<div class="container">
  <div style="padding-top:40px;">
    <%= content_tag(:p, notice, class: 'alert alert-success') if notice %>
    <%= content_tag(:p, alert, class: 'alert') if alert %>
  </div>
    <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<h3>Ask a Question</h3>
  <%= form_for @post do |f| %>
    <div>
      <%= f.label :Question %>
      <%= f.text_area :post %>
    </div>

    <%= f.submit :class => "btn btn-primary" %>
  <% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% if current_user.present? %>
  <%= render 'form' %>
  <% else %>

<% end %>
<ul class="nav nav-tabs">
  <li class="active"><a href="#recent" data-toggle="tab">Recent Questions</a></li>
  <% if current_user.present? %>
  <li><a href="#myposts" data-toggle="tab">My Posts</a></li>
  <% else %>

  <% end %>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="recent">
    <% @recentposts.each do |post| %>
      <div class="post">
        <%= post.post %> - <small><%= time_ago_in_words(post.created_at) %></small>
      </div>
    <% end %>
    <%= paginate @recentposts %>
  </div>
  <div class="tab-pane" id="myposts">
    <% if current_user.present?  && @myposts.count >= 1 %>
      <table>
        <% @myposts.each do |post| %>
        <tr>
          <td><%= post.post %></td>
          <td>
          </td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Show', post_path(post) %></td>
          <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <% end %>
      </table>
    <% else %>
    <p>You have not yet created any posts. Starting learning more about your pet now by creating your first question below.</p>
      <%= render 'form' %>
    <% end %>
  </div>
</div>

<script>
  $(function () {
    $('#myTab a:last').tab('show');
  })
</script>

app/views/posts/new.html.erb
<% if current_user.present? %>
  <%= render 'form' %>
<% else %>
  <div>
    <%= link_to 'Sign in to ask a question.', login_path %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h3><%= @post.post %></h3>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<% if current_user %>
  <h1>Edit Profile</h1>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :Date_of_Birth %>
      <%= f.date_select :dob, start_year: 1910 %>
    </div>
    <div>
      <%= f.label :street_address %>
      <%= f.text_field :street_address %>
    </div>
    <div>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div>
      <%= f.label :state %>
      <%= f.select :state, options_from_collection_for_select(State.all, :id, :name) %>
    </div>

    <%= f.submit :class => "btn btn-primary" %>
  <% end %>

<% end %>

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
<li><%= user.email %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
  <%= form_for @user do |f| %>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit :class => "btn btn-primary" %>
  <% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>